# Plugins
plugins: [jekyll-paginate]

# Compile info
source: .
destination: _site
exclude: [README.md, Engine Relations.xml]
paginate: 1

# General site info
title: Game Engine History
undertitle: A Selective Overview
author:
  name: Luc van den Brand
